apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: use-vc
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DO_NOT_TRACK
            value: {{ .Values.service.doNotTrack | quote }}
          - name: INFINITY_URL_PREFIX
            value: {{ .Values.service.urlPrefix }}
          - name: SANDBOX_CPU_QUOTA
            value: {{ .Values.sandbox.cpuQuota | quote }}
          - name: SANDBOX_MEMORY_LIMIT
            value: {{ .Values.sandbox.memoryLimit | quote }}
          - name: SANDBOX_ALLOW_NETWORK
            value: {{ .Values.sandbox.allowNetwork | quote }}
          - name: SANDBOX_TIMEOUT_SECONDS
            value: {{ .Values.sandbox.timeoutSeconds | quote }}
          - name: SANDBOX_MAX_USER_PROGRESS
            value: {{ .Values.sandbox.maxUserProgress | quote }}
          - name: SANDBOX_POOL_SIZE
            value: {{ .Values.sandbox.poolSize | quote }}
          ports:
          - containerPort: {{ .Values.ports.apiPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.ports.apiPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
               memory: {{ .Values.resources.limits.memory }}
               cpu: {{ .Values.resources.limits.cpu }}
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
      tolerations: {{- toYaml .Values.tolerations | nindent 10 }}
