# Regular service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.ports.apiPort }}
      targetPort: {{ .Values.ports.apiPort }}
  selector:
    app: {{ .Release.Name }}
{{- if .Values.service.headless.enabled }}
---
# Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    service: headless
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.ports.apiPort }}
      targetPort: {{ .Values.ports.apiPort }}
  selector:
    app: {{ .Release.Name }}
{{- end }}
