{{- if .Values.runtimeNamespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.runtimeNamespace.name }}
  labels:
    name: {{ .Values.runtimeNamespace.name }}
    sandbox-platform: runtime
{{- end }}
