{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: s3fs-passwd
  namespace: {{ .Values.global.namespace | default "sandbox-system" }}
type: Opaque
stringData:
  s3fs-passwd: |
    {{ .Values.minio.auth.rootUser }}:{{ .Values.minio.auth.rootPassword }}
{{- end }}
