{{- if .Values.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ include "sandbox.fullname" . }}
type: Opaque
stringData:
  S3_ENDPOINT_URL: {{ .Values.controlPlane.s3.endpointUrl | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.secret.s3.accessKeyId | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secret.s3.secretAccessKey | quote }}
  S3_BUCKET: {{ .Values.controlPlane.s3.bucket | quote }}
  S3_REGION: {{ .Values.secret.s3.region | quote }}
  # MariaDB root password (if using internal MariaDB)
  {{- if .Values.mariadb.enabled }}
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | quote }}
  {{- end }}
{{- end }}
