{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sandbox.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "sandbox.fullname" . }}
    component: control-plane
{{- end }}
